FROM node:20-alpine AS build
ARG NODE_OPTIONS=--max-old-space-size=512
ENV NODE_OPTIONS=$NODE_OPTIONS
WORKDIR /app
COPY package.json pnpm-workspace.yaml turbo.json ./
COPY apps/api/package.json apps/api/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN corepack enable && pnpm install --no-frozen-lockfile
COPY . .
RUN pnpm --filter @websphere/shared build && pnpm --filter @websphere/api exec prisma generate --schema ../../prisma/schema.prisma && pnpm --filter @websphere/api build
CMD ["node", "apps/api/dist/main.js"]
