import { FormEvent, useEffect, useState } from 'react';
import { request } from '../api';
import { GroupHub } from './GroupHub';
import type { GroupHub as GroupHubData, GroupSummary } from './types';

type Props = { userId: string; selectedGroupId: string; onSelectGroup: (id: string) => void; onIdeas: () => void; onChat: () => void; notify: (message: string) => void };

export function GroupsPage({ userId, selectedGroupId, onSelectGroup, onIdeas, onChat, notify }: Props) {
  const [groups, setGroups] = useState<GroupSummary[] | null>(null);
  const [hub, setHub] = useState<GroupHubData | null>(null);
  const [dialog, setDialog] = useState<'create' | 'join' | 'hub' | null>(null);
  async function refresh(preferred?: string) { const next = await request<GroupSummary[]>('/groups'); setGroups(next); if (preferred) onSelectGroup(preferred); }
  async function loadHub(id: string) { setHub(await request<GroupHubData>(`/groups/${id}/hub`)); }
  useEffect(() => { void refresh().catch((error: Error) => notify(error.message)); }, []);
  async function openHub(id: string) { onSelectGroup(id); await loadHub(id); setDialog('hub'); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const name = String(new FormData(form).get('name') ?? '').trim(); if (!name) return; try { const value = await request<{ id: string }>('/groups', { method: 'POST', body: JSON.stringify({ name }) }); form.reset(); await refresh(value.id); setDialog(null); notify('Group created.'); } catch (error: any) { notify(error.message); } }
  async function join(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const code = String(new FormData(form).get('code') ?? '').trim(); if (!code) return; try { const value = await request<{ id: string }>('/groups/join', { method: 'POST', body: JSON.stringify({ code }) }); form.reset(); await refresh(value.id); setDialog(null); notify('You joined the group.'); } catch (error: any) { notify(error.message); } }
  async function add(email: string) { try { await request(`/groups/${selectedGroupId}/members`, { method: 'POST', body: JSON.stringify({ email }) }); await loadHub(selectedGroupId); notify('Member added.'); } catch (error: any) { notify(error.message); } }
  async function remove(id: string) { if (!confirm('Remove this member from the group?')) return; try { await request(`/groups/${selectedGroupId}/members/${id}`, { method: 'DELETE' }); await loadHub(selectedGroupId); notify('Member removed.'); } catch (error: any) { notify(error.message); } }
  return <section className="sp on"><div className="ph"><h2>My Groups</h2><div className="ph-acts"><button className="btn-o btn-sm" onClick={() => setDialog('join')}>Join Group</button><button className="btn btn-sm" onClick={() => setDialog('create')}>Create Group</button></div></div><div className="cc groups-card">{groups === null ? <div className="legacy-empty">Loading groups…</div> : groups.length ? groups.map((group) => <div className="group-row" key={group.id}><span className="group-row-icon">{group.name.slice(0, 1).toUpperCase()}</span><div className="group-row-info"><strong>{group.name}</strong><span>{group.members[0]?.role === 'Project_Leader' ? 'You are the Leader' : 'You are a Member'} · {group._count.projects} projects · {group._count.ideas} ideas</span></div><span className="bdg ac">{group.members[0]?.role === 'Project_Leader' ? 'Leader' : 'Member'}</span><button className="btn-o btn-sm" onClick={() => void openHub(group.id)}>Group Hub</button><button className="btn btn-sm" onClick={() => { onSelectGroup(group.id); onChat(); }}>Open Chat</button></div>) : <div className="legacy-empty"><strong>Your workspace is ready</strong><span>Your groups will appear here after you create one or accept an invitation.</span><div><button className="btn-o btn-sm" onClick={() => setDialog('join')}>Join Group</button><button className="btn btn-sm" onClick={() => setDialog('create')}>Create Group</button></div></div>}</div>{dialog ? <div className="modal-ov open" onMouseDown={(event) => { if (event.target === event.currentTarget) setDialog(null); }}><div className={`modal-box ${dialog === 'hub' ? 'hub-modal' : ''}`}><div className="modal-ttl"><span>{dialog === 'create' ? 'Create Group' : dialog === 'join' ? 'Join Group' : 'Group Hub'}</span><button className="modal-close" onClick={() => setDialog(null)}>×</button></div>{dialog === 'create' ? <form onSubmit={create}><label className="lbl">Group Name</label><input className="ifield" name="name" placeholder="Your group name" required /><div className="modal-acts"><button type="button" className="btn-o" onClick={() => setDialog(null)}>Cancel</button><button className="btn">Create Group</button></div></form> : null}{dialog === 'join' ? <form onSubmit={join}><label className="lbl">Invitation Code</label><input className="ifield" name="code" placeholder="Enter invitation code" required /><div className="modal-acts"><button type="button" className="btn-o" onClick={() => setDialog(null)}>Cancel</button><button className="btn">Join Group</button></div></form> : null}{dialog === 'hub' && hub ? <GroupHub hub={hub} notify={notify} onAdd={add} onIdeas={onIdeas} onRemove={remove} userId={userId} /> : null}</div></div> : null}</section>;
}
