import { Body, Controller, Delete, Get, Headers, HttpException, Param, Patch, Post, Put, Query, Redirect, StreamableFile, UploadedFile, UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { z } from 'zod';
import { aiAskSchema, calendarEventSchema, ideaSchema, loginSchema, passwordChangeSchema, passwordForgotSchema, passwordResetSchema, profileUpdateSchema, pushSubscriptionSchema, pushUnsubscribeSchema, registrationOtpRequestSchema, projectSchema, resourceLinkSchema, resourceUpdateSchema, supportTicketSchema, taskSchema, taskStatusSchema, verifiedRegisterSchema } from '@websphere/shared';
import { AppService } from './app.service.js';
import { LocalStorageService } from './local-storage.service.js';
import { RedisService } from './redis.service.js';
import { GroupScope, ProjectScope, Public, Roles } from './auth.decorators.js';
import { RealtimeGateway } from './realtime.gateway.js';
import { TurnService } from './turn.service.js';

const parse = <T>(schema: z.ZodType<T>, value: unknown) => { const result = schema.safeParse(value); if (!result.success) { const fields = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0] ?? 'body'), issue.message])); throw new HttpException({ code: 'VALIDATION_FAILED', message: 'One or more fields are invalid', fields }, 400); } return result.data; };

@Controller()
export class AppController {
  constructor(private readonly app: AppService, private readonly storage: LocalStorageService, private readonly redis: RedisService, private readonly realtime: RealtimeGateway, private readonly turn: TurnService) {}
  private caller(auth?: string) { return this.app.caller(auth); }
  @Public() @Get('health') async health() { await this.app.prisma.$queryRaw`SELECT 1`; await this.redis.ping(); return { ok: true, database: 'up', redis: 'up', timestamp: new Date().toISOString() }; }
  @Public() @Post('auth/registration/otp') registrationOtp(@Body() body: unknown) { return this.app.sendRegistrationOtp(parse(registrationOtpRequestSchema, body).email); }
  @Public() @Post(['users', 'auth/register']) register(@Body() body: unknown) { return this.app.register(parse(verifiedRegisterSchema, body)); }
  @Public() @Post('auth/login') login(@Body() body: unknown) { const input = parse(loginSchema, body); return this.app.login(input.email, input.password); }
  @Public() @Post('auth/admin/login') adminLogin(@Body() body: unknown) { const input = parse(loginSchema, body); return this.app.login(input.email, input.password, true); }
  @Public() @Post('auth/refresh') refresh(@Body('refresh') refresh: string) { return this.app.refreshToken(refresh); }
  @Post('auth/logout') async logout(@Headers('authorization') auth?: string) { return this.app.logout(await this.caller(auth)); }
  @Public() @Post('auth/password/change') async change(@Headers('authorization') auth: string, @Body() body: unknown) { const input = parse(passwordChangeSchema, body); return this.app.changePassword(await this.app.caller(auth, { allowLocked: true }), input.oldPassword, input.password, input.confirm); }
  @Public() @Post('auth/password/forgot') forgot(@Body() body: unknown) { return this.app.forgot(parse(passwordForgotSchema, body).email); }
  @Public() @Post('auth/password/reset') reset(@Body() body: unknown) { const input = parse(passwordResetSchema, body); return this.app.resetPassword(input.token, input.password, input.confirm); }
  @Get('users/me') async me(@Headers('authorization') auth: string) { return this.app.me(await this.caller(auth)); }
  @Patch('users/me') async updateMe(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.updateMe(await this.caller(auth), parse(profileUpdateSchema, body)); }
  @Post('users/me/avatar') @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 5 * 1024 * 1024, files: 1 } }))
  async avatar(@Headers('authorization') auth: string, @UploadedFile() file?: { originalname: string; mimetype: string; buffer: Buffer }) { if (!file) throw new HttpException({ code: 'VALIDATION_FAILED', message: 'Choose an avatar image', fields: { file: 'required' } }, 400); const avatarUrl = await this.storage.saveAvatar(file); return this.app.updateMe(await this.caller(auth), { avatarUrl }); }
  @Public() @Get('uploads/:fileName') async upload(@Param('fileName') fileName: string) { return new StreamableFile(await this.storage.readPublicFile(fileName)); }

  @Post('groups') async createGroup(@Headers('authorization') auth: string, @Body('name') name: string) { return this.app.createGroup(await this.caller(auth), name); }
  @Post('groups/join') async joinGroup(@Headers('authorization') auth: string, @Body('code') code: string) { return this.app.joinGroup(await this.caller(auth), code); }
  @Get('groups') async groups(@Headers('authorization') auth: string) { return this.app.groups(await this.caller(auth)); }
  @GroupScope() @Get('groups/:id') async group(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.group(await this.caller(auth), id); }
  @GroupScope() @Post('groups/:id/members') async addMember(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: { userId?: string; email?: string }) { const caller = await this.caller(auth); if (body.email) return this.app.addGroupMemberByEmail(caller, id, body.email.trim().toLowerCase()); if (body.userId) return this.app.addGroupMember(caller, id, body.userId); throw new HttpException({ code: 'VALIDATION_FAILED', message: 'Provide a member email address or user ID' }, 400); }
  @GroupScope() @Delete('groups/:id/members/:userId') async removeMember(@Headers('authorization') auth: string, @Param() p: any) { return this.app.removeGroupMember(await this.caller(auth), p.id, p.userId); }
  @GroupScope() @Get('groups/:id/hub') async hub(@Headers('authorization') auth: string, @Param('id') id: string) { const caller = await this.caller(auth); await this.app.member(id, caller.id); const [group, ideas, messages, poll] = await Promise.all([this.app.group(caller, id), this.app.ideas(caller, id), this.app.prisma.chatMessage.findMany({ where: { groupId: id }, orderBy: { createdAt: 'desc' }, take: 50 }), this.app.prisma.ideaPoll.findFirst({ where: { groupId: id, open: true }, orderBy: { createdAt: 'desc' }, select: { id: true } })]); return { group, ideas, messages, poll: poll ? await this.app.pollResults(caller, poll.id) : null }; }
  @GroupScope() @Get('groups/:id/messages') async messages(@Headers('authorization') auth: string, @Param('id') id: string, @Query('cursor') cursor?: string) { const caller = await this.caller(auth); await this.app.member(id, caller.id); return this.app.prisma.chatMessage.findMany({ where: { groupId: id, ...(cursor ? { id: { lt: cursor } } : {}) }, orderBy: { createdAt: 'desc' }, take: 50 }); }
  @GroupScope() @Get('groups/:id/realtime/ice-servers') async iceServers(@Headers('authorization') auth: string, @Param('id') id: string) { const caller = await this.caller(auth); await this.app.member(id, caller.id); return { iceServers: this.turn.iceServers(caller.id) }; }

  @GroupScope() @Post('groups/:id/ideas') async idea(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.idea(await this.caller(auth), id, parse(ideaSchema, body)); }
  @GroupScope() @Get('groups/:id/ideas') async ideas(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.ideas(await this.caller(auth), id); }
  @Patch('ideas/:id') async revise(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.reviseIdea(await this.caller(auth), id, parse(ideaSchema, body)); }
  @Post('ideas/:id/reject') async rejectIdea(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.rejectIdea(await this.caller(auth), id); }
  @GroupScope() @Post('groups/:id/ideas/merge') async mergeIdeas(@Headers('authorization') auth: string, @Param('id') id: string, @Body('ideaIds') ideaIds: string[]) { return this.app.mergeIdeas(await this.caller(auth), id, ideaIds); }
  @GroupScope() @Post('groups/:id/polls') async poll(@Headers('authorization') auth: string, @Param('id') id: string, @Body('ideaIds') ideaIds: string[]) { return this.app.openPoll(await this.caller(auth), id, ideaIds); }
  @Post('polls/:id/vote') async vote(@Headers('authorization') auth: string, @Param('id') id: string, @Body('optionId') optionId: string) { const tally = await this.app.vote(await this.caller(auth), id, optionId); this.realtime.publishPollTally(tally.groupId, tally); return tally; }
  @Get('polls/:id/results') async results(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.pollResults(await this.caller(auth), id); }
  @GroupScope('groupId') @Post('groups/:groupId/ideas/:ideaId/begin') async begin(@Headers('authorization') auth: string, @Param() params: any) { return this.app.begin(await this.caller(auth), params.groupId, params.ideaId); }
  @Post('ideas/:id/ai/suggest') async ideaSuggestion(@Headers('authorization') auth: string, @Param('id') id: string) { const caller = await this.caller(auth); const idea = await this.app.prisma.idea.findUniqueOrThrow({ where: { id } }); if (idea.authorId !== caller.id) throw new Error('RBAC_FORBIDDEN'); return { ideaId: id, suggestions: [{ action: 'revise', title: idea.title, body: `${idea.body}\n\nConsider adding measurable objectives and intended users.` }] }; }

  @Post('projects') async createProject(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.createProject(await this.caller(auth), parse(projectSchema, body)); }
  @Get('projects') async projects(@Headers('authorization') auth: string) { return this.app.projects(await this.caller(auth)); }
  @ProjectScope() @Get('projects/:id') async project(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.project(await this.caller(auth), id); }
  @ProjectScope() @Patch('projects/:id') async updateProject(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.updateProject(await this.caller(auth), id, body); }
  @ProjectScope() @Patch('projects/:id/status') async statusProject(@Headers('authorization') auth: string, @Param('id') id: string, @Body('status') status: string) { return this.app.updateProject(await this.caller(auth), id, { status }); }
  @ProjectScope() @Get('projects/:id/team') async team(@Headers('authorization') auth: string, @Param('id') id: string) { const project = await this.app.project(await this.caller(auth), id); return project.members; }
  @ProjectScope() @Patch('projects/:id/team/:userId') async updateResponsibility(@Headers('authorization') auth: string, @Param('id') id: string, @Param('userId') userId: string, @Body('responsibility') responsibility: string) { return this.app.updateResponsibility(await this.caller(auth), id, userId, responsibility); }
  @ProjectScope() @Post('projects/:id/members') async addProjectMember(@Headers('authorization') auth: string, @Param('id') id: string, @Body('userId') userId: string) { return this.app.addProjectMember(await this.caller(auth), id, userId); }
  @ProjectScope() @Get('projects/:id/progress') async progress(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.projectProgress(await this.caller(auth), id); }
  @ProjectScope() @Post('projects/:id/tasks') async createTask(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.createTask(await this.caller(auth), id, parse(taskSchema, body)); }
  @ProjectScope() @Get('projects/:id/tasks/tracker') async tracker(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.tracker(await this.caller(auth), id); }
  @ProjectScope() @Get('projects/:id/tasks/by-member') async byMember(@Headers('authorization') auth: string, @Param('id') projectId: string) { const caller = await this.caller(auth); const project = await this.app.project(caller, projectId); return project.members.map((member: any) => ({ member: member.user, pending: project.tasks.filter((task: any) => task.status === 'pending' && task.assignments.some((a: any) => a.assigneeId === member.userId)).length, ongoing: project.tasks.filter((task: any) => task.status === 'ongoing' && task.assignments.some((a: any) => a.assigneeId === member.userId)).length, for_review: project.tasks.filter((task: any) => task.status === 'for_review' && task.assignments.some((a: any) => a.assigneeId === member.userId)).length, completed: project.tasks.filter((task: any) => task.status === 'completed' && task.assignments.some((a: any) => a.assigneeId === member.userId)).length })); }
  @Get('tasks/mine') async mine(@Headers('authorization') auth: string, @Query() query: any) { return this.app.myTasks(await this.caller(auth), query); }
  @Get('tasks/tracker') async taskTracker(@Headers('authorization') auth: string) { return this.app.taskTracker(await this.caller(auth)); }
  @Post('tasks/:id/resources') async linkTaskResource(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.linkTaskResource(await this.caller(auth), id, parse(resourceLinkSchema, body)); }
  @Get('tasks/:id') async task(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.task(await this.caller(auth), id); }
  @Patch('tasks/:id') async updateTask(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.updateTask(await this.caller(auth), id, parse(taskSchema.partial(), body)); }
  @Post('tasks/:id/assign') async assign(@Headers('authorization') auth: string, @Param('id') id: string, @Body('assigneeId') assigneeId: string) { const result = await this.app.assignTask(await this.caller(auth), id, assigneeId); const task = await this.app.prisma.task.findUnique({ where: { id }, select: { projectId: true } }); if (task) this.realtime.publishTaskUpdated(task.projectId, await this.app.task(await this.caller(auth), id)); return result; }
  @Patch('tasks/:id/status') async taskStatus(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { const caller = await this.caller(auth); const updated = await this.app.taskStatus(caller, id, parse(taskStatusSchema, body).status); this.realtime.publishTaskUpdated(updated.projectId, await this.app.task(caller, id)); return updated; }

  @Get('dashboard') async dashboard(@Headers('authorization') auth: string) { const caller = await this.caller(auth); const [projects, tasks, notifications] = await Promise.all([this.app.projects(caller), this.app.myTasks(caller, {}), this.app.notifications(caller)]); return { glance: { activeProjects: projects.filter((p: any) => p.status === 'active').length, pendingTasks: tasks.filter((t: any) => t.status === 'pending').length, ideasSubmitted: await this.app.prisma.idea.count({ where: { authorId: caller.id } }) }, projects, tasks: tasks.slice(0, 8), notifications: notifications.slice(0, 8) }; }
  @Get('calendar') async calendar(@Headers('authorization') auth: string, @Query('from') from?: string, @Query('to') to?: string) { return this.app.calendar(await this.caller(auth), from, to); }
  @Post('calendar/events') async createEvent(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.createCalendarEvent(await this.caller(auth), parse(calendarEventSchema, body)); }
  @Patch('calendar/events/:id') async updateEvent(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.updateCalendarEvent(await this.caller(auth), id, parse(calendarEventSchema.partial(), body)); }
  @Delete('calendar/events/:id') async deleteEvent(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.deleteCalendarEvent(await this.caller(auth), id); }
  @Get('calendar/upcoming') async upcoming(@Headers('authorization') auth: string) { const data = await this.app.calendar(await this.caller(auth)); return data.hints.filter((hint: any) => hint.deadline).sort((a: any, b: any) => +new Date(a.deadline) - +new Date(b.deadline)); }

  @Get('notifications') async notifications(@Headers('authorization') auth: string) { return this.app.notifications(await this.caller(auth)); }
  @Patch('notifications/:id/read') async read(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.markRead(await this.caller(auth), id); }
  @Get('notifications/preferences') async preference(@Headers('authorization') auth: string) { return this.app.preferences(await this.caller(auth)); }
  @Put('notifications/preferences') async setPreference(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.preferences(await this.caller(auth), body); }
  @Public() @Get('push/config') pushConfig() { return this.app.pushConfig(); }
  @Post('push/subscribe') async subscribe(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.subscribePush(await this.caller(auth), parse(pushSubscriptionSchema, body)); }
  @Delete('push/subscribe') async unsubscribe(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.unsubscribePush(await this.caller(auth), parse(pushUnsubscribeSchema, body).endpoint); }

  @Post('ai/ask') async ask(@Headers('authorization') auth: string, @Body() body: unknown) { const input = parse(aiAskSchema, body); return this.app.ai(await this.caller(auth), input.prompt, input); }
  @Post('ai/planning') async planning(@Headers('authorization') auth: string, @Body() body: unknown) { const input = parse(aiAskSchema, body); return this.app.ai(await this.caller(auth), input.prompt, input); }
  @Post('ai/ideas/generate') async generate(@Headers('authorization') auth: string, @Body() body: unknown) { const input = parse(aiAskSchema, body); return this.app.ai(await this.caller(auth), input.prompt, input); }
  @Post('ai/recommendations') async aiRecommendations(@Headers('authorization') auth: string, @Body('prompt') prompt: string) { const caller = await this.caller(auth); const tools = await this.app.integrations(caller); return { prompt, recommendations: tools.map((tool: any) => ({ provider: tool.provider, name: tool.name, category: tool.category })) }; }
  @Get('projects/:id/analytics') async analytics(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.analytics(await this.caller(auth), id); }
  @Get('projects/:id/analytics/trends') async analyticsTrends(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.analyticsTrends(await this.caller(auth), id); }
  @Get('projects/:id/analytics/summary') async analyticsSummary(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.analyticsSummary(await this.caller(auth), id); }
  @Get('projects/:id/risk') async risk(@Headers('authorization') auth: string, @Param('id') id: string) { const data = await this.app.analytics(await this.caller(auth), id); return { riskScore: data.riskScore, riskLevel: data.riskLevel }; }
  @Get('projects/:id/prediction') async prediction(@Headers('authorization') auth: string, @Param('id') id: string) { const data = await this.app.analytics(await this.caller(auth), id); return { predictedCompletion: data.predictedCompletion, deltaDays: data.deltaDays, factors: data.bottlenecks }; }
  @Get('projects/:id/recommendations') async recommendations(@Headers('authorization') auth: string, @Param('id') id: string) { return (await this.app.analytics(await this.caller(auth), id)).recommendations; }

  @Get('integrations/catalog') async catalog(@Headers('authorization') auth: string) { return this.app.integrations(await this.caller(auth)); }
  @Get('integrations/:provider/authorize') async authorize(@Headers('authorization') auth: string, @Param('provider') provider: any, @Query('redirectUri') redirectUri: string) { return this.app.oauthAuthorize(await this.caller(auth), provider, redirectUri); }
  @Public() @Redirect() @Get('integrations/:provider/callback') async callback(@Param('provider') provider: any, @Query('code') code: string, @Query('state') state: string, @Query('redirectUri') redirectUri?: string) { await this.app.oauthCallback(provider, code, state, redirectUri); const destination = new URL('/integrations', process.env.WEB_ORIGIN ?? 'http://localhost:5173'); destination.searchParams.set('connected', String(provider)); return { url: destination.toString(), statusCode: 302 }; }
  @Get('integrations/connections') async connections(@Headers('authorization') auth: string) { return this.app.integrationConnections(await this.caller(auth)); }
  @Get('integrations/connections/:id/google-picker-token') async googlePickerToken(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.googlePickerToken(await this.caller(auth), id); }
  @Post('integrations/connections/:id/sync') async sync(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.syncIntegration(await this.caller(auth), id); }
  @Post('resources/:id/launch') async launchResource(@Headers('authorization') auth: string, @Param('id') id: string) { return this.app.launchResource(await this.caller(auth), id); }
  @Patch('resources/:id') async updateResource(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { const caller = await this.caller(auth); const updated = await this.app.updateLinkedResource(caller, id, parse(resourceUpdateSchema, body)); this.realtime.publishTaskUpdated(updated.projectId, await this.app.task(caller, updated.taskId)); return updated; }
  @Post('support/tickets') async ticket(@Headers('authorization') auth: string, @Body() body: unknown) { return this.app.ticket(await this.caller(auth), parse(supportTicketSchema, body)); }
  @Roles('Administrator') @Get('admin/monitoring') async monitoring(@Headers('authorization') auth: string) { return this.app.monitoring(await this.caller(auth)); }
  @Roles('Administrator') @Get('admin/support/tickets') async supportTickets(@Headers('authorization') auth: string) { return this.app.adminSupportTickets(await this.caller(auth)); }
  @Roles('Administrator') @Get('admin/users') async users(@Headers('authorization') auth: string) { const caller = await this.caller(auth); await this.app.admin(caller); return this.app.prisma.user.findMany({ select: { id: true, email: true, fullName: true, role: true, status: true, createdAt: true } }); }
  @Roles('Administrator') @Patch('admin/users/:id') async adminUser(@Headers('authorization') auth: string, @Param('id') id: string, @Body() body: unknown) { return this.app.adminUpdateUser(await this.caller(auth), id, body); }
  @Roles('Administrator') @Get('admin/logs') async logs(@Headers('authorization') auth: string) { const caller = await this.caller(auth); await this.app.admin(caller); return this.app.prisma.auditLog.findMany({ orderBy: { createdAt: 'desc' } }); }
  @Roles('Administrator') @Get('admin/settings') async settings(@Headers('authorization') auth: string) { const caller = await this.caller(auth); await this.app.admin(caller); return this.app.prisma.systemSetting.findMany(); }
  @Roles('Administrator') @Put('admin/settings') async setSettings(@Headers('authorization') auth: string, @Body() body: Record<string, unknown>) { const caller = await this.caller(auth); await this.app.admin(caller); return Promise.all(Object.entries(body).map(([key, value]) => this.app.prisma.systemSetting.upsert({ where: { key }, update: { value: value as any, updatedBy: caller.id }, create: { key, value: value as any, updatedBy: caller.id } }))); }
}
